/* GENERATED by scripts/build-featured.mjs — do not edit by hand.

   Dimensions travel with the images so next/image can reserve the right box
   before anything downloads. Without them every card would reflow on load,
   which is a cumulative layout shift on the busiest page of the site.

   A project absent from this map has NO featured image, and the card falls
   back to its generated signature. That is the correct behaviour for the
   projects with no public UI to photograph — see the header of the build
   script for why a mocked-up screenshot is not an option.
*/

export type Featured = {
  width: number
  height: number
  /** Inlined 16px blur, shown while the real image downloads. */
  blurDataURL: string
}

export const FEATURED: Record<string, Featured> = {
  'crm': {
    width: 2400,
    height: 1500,
    blurDataURL:
      'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAoAA4BaJZwAAueLJjKAAAD+0r35Ov3j1RfDS2E8XXEfiuaCLsEry8SJFYZ9eJzyM15y3T9w1CZ9oLzEdKbH0a+pijtywoPVmGQ7YgQAAA==',
  },
  'chefs-and-homes': {
    width: 2400,
    height: 1500,
    blurDataURL:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAoAA4BaJaQAAucevabAAP73wYXJC3HPjONNKIxS/vLZKa0os60pOMmNzPXMEdrDTNYiNa4vBmbc727hLGAA',
  },
  'zyvren': {
    width: 2400,
    height: 1500,
    blurDataURL:
      'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAoAA4BaJZQCdAERA3X8En1eAAD+98dp788bAywRmch2E81/+Fe2rYPbzw71XwA1ki2YlWUPwJU7BzXuWuAXG8MJBAAA',
  },
  'women-wellness-first': {
    width: 2400,
    height: 1500,
    blurDataURL:
      'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAoAA4BaJYwCdAYvrvvLk0gAAP7qXdm3sFfqOeW10dohL277BI2wgIQBEd++Z/Mt89tSnXUe44RT1CgQNDccXIRoErVxAnZiGEAKZA9ENIAA',
  },
  'allure-dental': {
    width: 2400,
    height: 1500,
    blurDataURL:
      'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAoAA4BaJZQAAueJ8GzcgAD+8byVW/AB7JZUPlAG+xRuze9QjcXV6IfGfCsHNwEw1/cyKuJaEUCxIu9IGo703Sg0HJ8GEAA=',
  },
  'mariforce': {
    width: 2400,
    height: 1500,
    blurDataURL:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQAAoAA4BaJZQCdAEPNFggAP7272bRb9vudf7x5pNhovKCzVcfaRS59HwaNeqQ4QAXg9x8AAA=',
  },
  'swann-bookkeeping': {
    width: 2400,
    height: 1500,
    blurDataURL:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAoAA4BaJQAAXFTH/gwAAP7SvBL0UZ9VpO1ynqXkL4XD5WSS4fLFe0YiPOmLeIvrJY8kdllHbNDH55AZ0+PF5eAAAA==',
  },
  'mirasphere-site': {
    width: 2400,
    height: 1500,
    blurDataURL:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAoAA4BaJZQAAq4JvzmX7sAA/vfBhGhynIjCWERsgVlWF9xQWayEWvGLtiVfDZI1pxm91GpSLYnKAAA=',
  },
}

export function featuredFor(slug: string): Featured | undefined {
  return FEATURED[slug]
}
