/* ==========================================================================
   LAB DATA BUILD

   Turns the RAG index (23 real chunks of Dheeraj's CV, FAQ, intros and
   project write-ups, each with a 384-dimension bge-small-en-v1.5 embedding)
   into a small module the Lab instruments can import: content/lab-data.ts.

   Two pieces of maths run here rather than in the browser, and for the same
   reason in both cases — the inputs never change between deploys, so paying
   for them at request time would be paying twice for one answer:

     1. PCA down to two dimensions, so the embedding map can plot the corpus.
        The 384-float vectors are 94 KB of JSON; the projected coordinates are
        under 2 KB. Shipping the vectors to project them client-side would
        cost forty times the payload to compute a constant.

     2. A byte-pair-encoding merge table trained on the same 23 chunks, so the
        tokeniser instrument runs a real BPE rather than importing a 2 MB
        production vocabulary or faking it with a regex.

   Run:  npm run build:lab
   Input:  the staged RAG index (see INDEX_CANDIDATES below)
   Output: content/lab-data.ts

   The generated file is committed. It is deterministic given the same index,
   so a diff in it always means the corpus changed.
   ========================================================================== */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

/* --- Input ---------------------------------------------------------------- */

/** The index lives outside the repo (it is generated by the RAG pipeline), so
    look in the places it is staged rather than hardcoding one path. */
const INDEX_CANDIDATES = [
  process.env.LAB_INDEX,
  '/mnt/user-data/uploads/dev/portfolio-scaffold/portfolio/public/index.json',
  join(process.cwd(), 'public/index.json'),
  join(process.cwd(), 'content/lab-index.json'),
].filter((path): path is string => typeof path === 'string' && path.length > 0)

const OUT_PATH = resolve(process.cwd(), 'content/lab-data.ts')

type Chunk = {
  id: string
  source: string
  text: string
  embedding: number[]
}

function loadIndex(): Chunk[] {
  const found = INDEX_CANDIDATES.find((path) => existsSync(path))
  if (!found) {
    console.error('build-lab-data: no index.json found. Looked in:')
    for (const path of INDEX_CANDIDATES) console.error(`  ${path}`)
    console.error('Set LAB_INDEX=/path/to/index.json to point at it.')
    process.exit(1)
  }

  const parsed: unknown = JSON.parse(readFileSync(found, 'utf8'))
  if (!Array.isArray(parsed)) {
    console.error(`build-lab-data: ${found} is not an array of chunks.`)
    process.exit(1)
  }

  const chunks: Chunk[] = []
  for (const raw of parsed) {
    if (typeof raw !== 'object' || raw === null) continue
    const record = raw as Record<string, unknown>
    const { id, source, text, embedding } = record
    if (
      typeof id !== 'string' ||
      typeof source !== 'string' ||
      typeof text !== 'string' ||
      !Array.isArray(embedding)
    ) {
      console.error(`build-lab-data: chunk ${String(id)} is malformed.`)
      process.exit(1)
    }
    chunks.push({ id, source, text, embedding: embedding.map(Number) })
  }

  if (chunks.length === 0) {
    console.error('build-lab-data: index contained no usable chunks.')
    process.exit(1)
  }

  // Every vector must share a dimension or the covariance is meaningless.
  const dims = new Set(chunks.map((c) => c.embedding.length))
  if (dims.size !== 1) {
    console.error(`build-lab-data: mixed embedding dimensions (${[...dims].join(', ')}).`)
    process.exit(1)
  }

  console.log(`build-lab-data: read ${chunks.length} chunks from ${found}`)
  return chunks
}

/* ==========================================================================
   PCA, FROM SCRATCH

   ── WHY NOT A LIBRARY ──────────────────────────────────────────────────────
   The obvious move is UMAP or t-SNE, and both would produce prettier
   clusters. Both are also stochastic, non-linear and have no inverse: there
   is no honest way to say what an axis MEANS, and no way to place a new point
   without re-fitting the whole embedding. PCA is a rotation. The axes are
   real directions in the 384-dimension space, the projection is a dot
   product, and the amount of structure it throws away is a number that can be
   printed rather than hand-waved. For an instrument whose entire point is
   showing what actually happens, reproducible and explainable beats pretty.

   ── WHY THE GRAM MATRIX AND NOT THE COVARIANCE ─────────────────────────────
   The covariance of 384-dimension data is a 384x384 matrix. With only 23
   samples its rank is at most 22, so 362 of those dimensions are structurally
   empty — iterating on it would be 280 times the arithmetic for identical
   answers. The Gram matrix G = X·Xᵗ is 23x23 and shares the same non-zero
   eigenvalues. Power iteration on it converges in milliseconds, and the
   projected scores fall out directly:

     G = X·Xᵗ,  G·u = λ·u,  v = Xᵗ·u / ‖Xᵗ·u‖ = Xᵗ·u / √λ
     scores = X·v = X·Xᵗ·u / √λ = λ·u / √λ = √λ · u

   so the first principal-component coordinate of every chunk is just √λ·u —
   no 384-dimension multiply needed. The component vector v is still computed,
   because it is what lets a future query be projected onto the same axes.

   ── WHY DEFLATION RATHER THAN A FULL EIGENSOLVER ───────────────────────────
   Only two components are wanted. Subtracting λ₁·u₁·u₁ᵗ from G removes the
   first component's contribution entirely, so a second power iteration on the
   deflated matrix finds the second. Two iterations, no eigensolver, and the
   result is exact to within the iteration tolerance.
   ========================================================================== */

/** Matrix-vector product for a symmetric n x n matrix stored row-major. */
function matVec(matrix: Float64Array, n: number, vector: Float64Array): Float64Array {
  const out = new Float64Array(n)
  for (let i = 0; i < n; i += 1) {
    let sum = 0
    const rowStart = i * n
    for (let j = 0; j < n; j += 1) sum += (matrix[rowStart + j] ?? 0) * (vector[j] ?? 0)
    out[i] = sum
  }
  return out
}

function norm(vector: Float64Array): number {
  let sum = 0
  for (let i = 0; i < vector.length; i += 1) sum += (vector[i] ?? 0) ** 2
  return Math.sqrt(sum)
}

/**
 * Dominant eigenpair of a symmetric matrix by power iteration.
 *
 * The starting vector is deterministic (a fixed low-discrepancy pattern rather
 * than Math.random) so two builds of the same corpus produce byte-identical
 * output. A random start would flip signs between runs and make every rebuild
 * look like a content change in the diff.
 */
function powerIteration(
  matrix: Float64Array,
  n: number,
  iterations = 2000,
  tolerance = 1e-12,
): { value: number; vector: Float64Array } {
  /* Annotated as bare `Float64Array` on purpose: that resolves to
     Float64Array<ArrayBufferLike>, which is what matVec returns, so the
     reassignment below type-checks without a cast. */
  let vector: Float64Array = new Float64Array(n)
  for (let i = 0; i < n; i += 1) vector[i] = Math.sin(i + 1) + 0.5

  let magnitude = norm(vector)
  for (let i = 0; i < n; i += 1) vector[i] = (vector[i] ?? 0) / magnitude

  let value = 0
  for (let step = 0; step < iterations; step += 1) {
    const next = matVec(matrix, n, vector)
    magnitude = norm(next)
    // A zero product means the matrix has no remaining variance in this
    // subspace (fully deflated). Report zero rather than dividing by it.
    if (magnitude < 1e-300) return { value: 0, vector }
    for (let i = 0; i < n; i += 1) next[i] = (next[i] ?? 0) / magnitude
    // Rayleigh quotient; for a unit vector this is vᵗ·M·v.
    let rayleigh = 0
    const product = matVec(matrix, n, next)
    for (let i = 0; i < n; i += 1) rayleigh += (next[i] ?? 0) * (product[i] ?? 0)
    const converged = Math.abs(rayleigh - value) < tolerance * Math.max(1, Math.abs(rayleigh))
    value = rayleigh
    vector = next
    if (converged && step > 8) break
  }
  return { value, vector }
}

type Projection = {
  coords: { x: number; y: number }[]
  component1: number[]
  component2: number[]
  mean: number[]
  explained: number
  explained1: number
  explained2: number
  scale: number
}

function pca2(chunks: Chunk[]): Projection {
  const n = chunks.length
  const first = chunks[0]
  if (!first) throw new Error('pca2 called with no chunks')
  const d = first.embedding.length

  /* Mean-centring is not optional. The vectors are L2-normalised, so they all
     sit on the unit sphere and share a large common direction; skipping the
     centring makes the first "component" that shared direction and wastes the
     axis on a constant. */
  const mean = new Float64Array(d)
  for (const chunk of chunks) {
    for (let j = 0; j < d; j += 1) mean[j] = (mean[j] ?? 0) + (chunk.embedding[j] ?? 0)
  }
  for (let j = 0; j < d; j += 1) mean[j] = (mean[j] ?? 0) / n

  const centred = new Float64Array(n * d)
  for (let i = 0; i < n; i += 1) {
    const embedding = chunks[i]?.embedding ?? []
    for (let j = 0; j < d; j += 1) {
      centred[i * d + j] = (embedding[j] ?? 0) - (mean[j] ?? 0)
    }
  }

  // Gram matrix G = X·Xᵗ (n x n, symmetric).
  const gram = new Float64Array(n * n)
  for (let i = 0; i < n; i += 1) {
    for (let k = i; k < n; k += 1) {
      let sum = 0
      for (let j = 0; j < d; j += 1) sum += (centred[i * d + j] ?? 0) * (centred[k * d + j] ?? 0)
      gram[i * n + k] = sum
      gram[k * n + i] = sum
    }
  }

  /* trace(G) is the total squared deviation of the corpus, which is total
     variance up to the same 1/(n-1) factor that divides out of the ratio. So
     the explained-variance figure printed in the generated file needs no
     scaling assumption — it is λ/trace, exactly. */
  let trace = 0
  for (let i = 0; i < n; i += 1) trace += gram[i * n + i] ?? 0

  const first_ = powerIteration(gram, n)

  // Deflate: remove the first component's rank-one contribution.
  const deflated = Float64Array.from(gram)
  for (let i = 0; i < n; i += 1) {
    for (let k = 0; k < n; k += 1) {
      deflated[i * n + k] =
        (deflated[i * n + k] ?? 0) -
        first_.value * (first_.vector[i] ?? 0) * (first_.vector[k] ?? 0)
    }
  }
  const second = powerIteration(deflated, n)

  // scores = √λ · u  (see the derivation in the block comment above).
  const root1 = Math.sqrt(Math.max(first_.value, 0))
  const root2 = Math.sqrt(Math.max(second.value, 0))
  const rawX = Array.from({ length: n }, (_, i) => root1 * (first_.vector[i] ?? 0))
  const rawY = Array.from({ length: n }, (_, i) => root2 * (second.vector[i] ?? 0))

  /* Sign is arbitrary in an eigenvector — u and -u are both valid. Pin it so
     the map does not mirror itself between builds: force the first chunk (the
     CV header) to land in the negative-x, negative-y quadrant. */
  const flipX = (rawX[0] ?? 0) > 0 ? -1 : 1
  const flipY = (rawY[0] ?? 0) > 0 ? -1 : 1

  /* ONE divisor for both axes, deliberately. Normalising each axis to fill
     [-1,1] independently would stretch the second component until it looked
     as important as the first, which is a lie the picture would tell for
     free. A shared scale keeps the aspect ratio truthful: the spread you see
     along y really is smaller than the spread along x. */
  let scale = 0
  for (let i = 0; i < n; i += 1) {
    scale = Math.max(scale, Math.abs(rawX[i] ?? 0), Math.abs(rawY[i] ?? 0))
  }
  if (scale === 0) scale = 1

  const coords = Array.from({ length: n }, (_, i) => ({
    x: (flipX * (rawX[i] ?? 0)) / scale,
    y: (flipY * (rawY[i] ?? 0)) / scale,
  }))

  // v = Xᵗ·u / √λ, with the same sign flip applied so the emitted component
  // vectors project a new point into the coordinate frame actually plotted.
  function componentVector(u: Float64Array, root: number, flip: number): number[] {
    const out = new Array<number>(d).fill(0)
    if (root === 0) return out
    for (let j = 0; j < d; j += 1) {
      let sum = 0
      for (let i = 0; i < n; i += 1) sum += (u[i] ?? 0) * (centred[i * d + j] ?? 0)
      out[j] = (flip * sum) / root
    }
    return out
  }

  return {
    coords,
    component1: componentVector(first_.vector, root1, flipX),
    component2: componentVector(second.vector, root2, flipY),
    mean: Array.from(mean),
    explained: trace > 0 ? (first_.value + second.value) / trace : 0,
    explained1: trace > 0 ? first_.value / trace : 0,
    explained2: trace > 0 ? second.value / trace : 0,
    scale,
  }
}

/* ==========================================================================
   LABELS

   Each point needs a name a human can read at a glance. The chunks are
   markdown with the whitespace collapsed, so the first phrase is almost
   always the heading it came from — cut it at the first boundary that reads
   like the end of a title and cap it at 40 characters on a word break.
   ========================================================================== */

const LABEL_MAX = 40

function labelFor(text: string): string {
  let head = text.replace(/\s+/g, ' ').trim()
  head = head.replace(/^[#*\-\s]+/, '')

  /* Boundaries, in the order they tend to appear: a question mark ends an FAQ
     heading; `**` starts the first bold field of a body; ` - ` starts the
     first bullet; a full stop ends a sentence. Take the earliest one that
     leaves something substantial behind. */
  const cuts: number[] = []
  const question = head.indexOf('?')
  if (question > 3) cuts.push(question + 1)
  for (const marker of ['**', ' - ', '. ', ' — ']) {
    const at = head.indexOf(marker)
    if (at > 3) cuts.push(at)
  }
  const cut = cuts.length > 0 ? Math.min(...cuts) : head.length
  head = head.slice(0, cut).trim()

  if (head.length > LABEL_MAX) {
    const clipped = head.slice(0, LABEL_MAX)
    const space = clipped.lastIndexOf(' ')
    head = (space > 12 ? clipped.slice(0, space) : clipped).trim()
  }

  // Trailing joiners look like a truncation bug rather than a label.
  head = head.replace(/[\s:;,\-—–(]+$/, '')
  return head.length > 0 ? head : 'untitled chunk'
}

/** `01-portfolio-rag` reads as noise in a legend; `portfolio-rag` does not. */
function sourceLabel(source: string): string {
  return source.replace(/^\d+[-_]/, '')
}

/* ==========================================================================
   BPE TRAINING

   ── WHY TRAIN ONE INSTEAD OF SHIPPING GPT'S ───────────────────────────────
   `gpt-tokenizer` is the honest-looking choice and the wrong one here: it is
   a ~2 MB vocabulary to make chips appear next to a textarea, which on a site
   that argues for performance would be an argument against itself. Training
   on the 23 chunks costs ~4 KB in the bundle and produces a tokeniser that is
   genuinely, verifiably real — the same greedy-merge algorithm, just a much
   smaller corpus. The instrument says so in as many words, and the smallness
   is the interesting part: it makes visible what a vocabulary IS by showing
   one that only knows this website.

   ── THE ALGORITHM ─────────────────────────────────────────────────────────
   Textbook BPE:
     1. Pre-tokenise, keeping each word's leading whitespace attached to it
        (GPT-2 does the same, which is why " the" and "the" are different
        tokens in every real model). Without this, merges leak across word
        boundaries and the vocabulary fills with junk like "e t".
     2. Represent every distinct pre-token as a list of characters, with the
        number of times it occurs in the corpus.
     3. Count every adjacent symbol pair, weighted by those occurrence counts.
     4. Merge the most frequent pair everywhere. Record it.
     5. Repeat 300 times.
   The ORDER of that list is the whole model: the encoder replays the merges
   by rank, which is why a merge table and not just a vocabulary is emitted.
   ========================================================================== */

const MERGE_TARGET = 300

/**
 * Key separator for pair lookups.
 *
 * It has to be a character the corpus cannot contain, and it cannot be a
 * space: tokens legitimately CONTAIN spaces (" the" is one symbol), so
 * `${a} ${b}` would make the pair ("a", " b") and the pair ("a ", "b")
 * produce the same key and silently mis-rank one of them. Written as an
 * escape rather than a literal NUL byte, because an invisible control
 * character in source is unreadable and confuses grep and editors.
 */
const PAIR_SEP = '\u0000'

/** Splits into pre-tokens, leading whitespace bound to the following word. */
export function preTokenise(text: string): string[] {
  return text.match(/\s*\S+|\s+/g) ?? []
}

type TrainedBpe = {
  merges: [string, string][]
  vocab: string[]
  baseChars: string[]
}

function trainBpe(chunks: Chunk[]): TrainedBpe {
  const frequencies = new Map<string, number>()
  for (const chunk of chunks) {
    for (const word of preTokenise(chunk.text)) {
      frequencies.set(word, (frequencies.get(word) ?? 0) + 1)
    }
  }

  // Array.from(string) splits on code points, not UTF-16 units, so an emoji
  // or an em dash stays one symbol instead of becoming two broken halves.
  const words: { symbols: string[]; freq: number }[] = []
  const baseChars = new Set<string>()
  for (const [word, freq] of frequencies) {
    const symbols = Array.from(word)
    for (const character of symbols) baseChars.add(character)
    words.push({ symbols, freq })
  }

  const merges: [string, string][] = []
  const learned = new Set<string>()

  for (let step = 0; step < MERGE_TARGET; step += 1) {
    const pairCounts = new Map<string, number>()
    for (const word of words) {
      const { symbols, freq } = word
      for (let i = 0; i < symbols.length - 1; i += 1) {
        const a = symbols[i]
        const b = symbols[i + 1]
        if (a === undefined || b === undefined) continue
        const key = `${a}${PAIR_SEP}${b}`
        pairCounts.set(key, (pairCounts.get(key) ?? 0) + freq)
      }
    }

    /* Pick the most frequent pair, breaking ties by the key so the result does
       not depend on Map iteration order. Determinism matters: the merge table
       is committed, and a rebuild that reshuffles equal-frequency merges would
       churn the diff for no semantic change. */
    let bestKey: string | null = null
    let bestCount = 0
    for (const [key, count] of pairCounts) {
      if (count > bestCount || (count === bestCount && bestKey !== null && key < bestKey)) {
        bestKey = key
        bestCount = count
      }
    }

    // Stop when nothing repeats: a merge seen once compresses nothing and only
    // memorises a single word in the corpus.
    if (bestKey === null || bestCount < 2) {
      console.log(
        `build-lab-data: BPE converged after ${step} merges (no pair occurs twice)`,
      )
      break
    }

    const [a = '', b = ''] = bestKey.split(PAIR_SEP)
    const merged = a + b
    merges.push([a, b])
    learned.add(merged)

    for (const word of words) {
      const { symbols } = word
      if (symbols.length < 2) continue
      const next: string[] = []
      let i = 0
      while (i < symbols.length) {
        const current = symbols[i]
        const following = symbols[i + 1]
        if (current === a && following === b) {
          next.push(merged)
          i += 2
        } else if (current !== undefined) {
          next.push(current)
          i += 1
        } else {
          i += 1
        }
      }
      word.symbols = next
    }
  }

  const sortedChars = [...baseChars].sort()
  return {
    merges,
    vocab: [...sortedChars, ...learned],
    baseChars: sortedChars,
  }
}

/* --- Encoder (mirrors components/lab/Tokenizer.tsx) -----------------------
   Duplicated here rather than imported so the script can report a real
   compression figure on the training corpus itself. Twenty lines of exact
   duplication is a better trade than a shared module that would drag the
   generated data into the build script's import graph.                     */

function encodeWith(merges: [string, string][], text: string): string[] {
  const ranks = new Map<string, number>()
  merges.forEach(([a, b], index) => ranks.set(`${a}${PAIR_SEP}${b}`, index))

  const out: string[] = []
  for (const word of preTokenise(text)) {
    const symbols = Array.from(word)
    while (symbols.length > 1) {
      let bestRank = Infinity
      let bestIndex = -1
      for (let i = 0; i < symbols.length - 1; i += 1) {
        const a = symbols[i]
        const b = symbols[i + 1]
        if (a === undefined || b === undefined) continue
        const rank = ranks.get(`${a}${PAIR_SEP}${b}`)
        if (rank !== undefined && rank < bestRank) {
          bestRank = rank
          bestIndex = i
        }
      }
      if (bestIndex < 0) break
      const a = symbols[bestIndex]
      const b = symbols[bestIndex + 1]
      if (a === undefined || b === undefined) break
      symbols.splice(bestIndex, 2, a + b)
    }
    out.push(...symbols)
  }
  return out
}

/* ==========================================================================
   ASK CORPUS — the retrieval index behind components/sections/AskPortfolio.tsx

   ── WHY THE RAG INDEX IS NOT ENOUGH ON ITS OWN ────────────────────────────
   The 23 chunks above are the corpus that was embedded, and they are real, but
   they were cut from the CV, the FAQ and the intros BEFORE the case studies
   existed. They describe the CRM as "Stack (frontend, backend, DB, hosting)"
   — an outline, not an answer. Meanwhile content/projects.ts contains the
   finished thing: 197 schema-validated routes, the IDOR the self-run security
   audit found, the RFC-4180 importer. A retrieval system that refuses "what
   did the security audit find?" while the answer sits two files away is not
   being honest, it is being under-indexed.

   So the retrieval corpus is the union: the 23 embedded chunks, plus chunks
   cut here from the site's own current content. Nothing is invented. Every
   supplementary chunk is prose already published on a route a visitor can
   open, which is exactly what makes the citation checkable.

   ── WHY THIS IS GENERATED RATHER THAN IMPORTED AT RUNTIME ─────────────────
   lib/retrieval.ts runs in the browser, so whatever it imports ships. Reaching
   for content/projects.ts directly would pull 40 KB of source — every stack
   rationale, every architecture node, every failure mode — into the home
   page's bundle to quote maybe six sentences of it. Cutting the chunks at
   build time ships the text and nothing else, and it means the corpus is a
   committed artefact: a diff in it is a content change, reviewable as one.

   The 23 embedded chunks are NOT copied in. The generated module imports
   LAB_POINTS and wraps them, because the Lab already ships that text on the
   same page — copying it would be paying for the corpus twice.
   ========================================================================== */

/** Longest a supplementary chunk may be, in characters.

    BM25's length normalisation (b = 0.75) handles uneven documents perfectly
    well, so this is not a scoring concern — it is a citation concern. The
    answer quotes whole sentences out of the winning chunk, and a chunk that
    spans two subjects will sometimes win on one and get quoted on the other.
    ~900 characters is around four sentences of this prose: long enough to keep
    a paragraph's argument intact, short enough that it is about one thing. */
const ASK_CHUNK_MAX = 900

/** Below this, a chunk is a fragment rather than a passage, and BM25's length
    normalisation turns it into a false positive magnet. Merged into a
    neighbour instead of indexed alone. */
const ASK_CHUNK_MIN = 140

/** Where the surviving embedded chunks can be read in context.

    The index predates the current routes, so the mapping cannot be derived and
    is stated here instead. Two sources have no page at all: the MERN store and
    the Virtuoso dashboards are CV entries rather than case studies, so they
    cite without a link rather than pointing at a 404. */
const INDEX_HREF: Record<string, string> = {
  cv: '/cv',
  faq: '/about',
  intros: '/about',
}

/* ==========================================================================
   SUPERSEDED CHUNKS — indexed for the map, NOT for answering

   The Lab plots all 23 chunks, and should: it is a picture of a corpus that
   was really embedded, and a picture is not a claim. Answering is different.
   An answer asserts. So eight of those chunks are excluded from the retrieval
   index, for two reasons, and both are about not saying false things.

   FIRST, four of them describe an architecture this site does not have. The
   index was cut while the plan was a language model in the browser — WebLLM,
   Qwen2.5 on WebGPU, transformers.js retrieval — and the site that shipped runs
   no model at all. Quoting "streaming inference on WebGPU via WebLLM" as a
   statement of fact, inside the very feature whose claim is "no model", would
   be the single worst thing this system could do. It would be a lie told by a
   machine built to be incapable of lying, which is worse than a wrong answer.

   SECOND, four of them are the pre-case-study OUTLINES of projects that now
   have full write-ups: bullet lists of open questions to himself ("Which stream
   — the CH Streaming API?", "Auth/multi-user model"), with empty **Metrics:**
   fields. content/projects.ts answers all of it properly. Leaving both in place
   means the outline sometimes outscores the finished article, because a
   question-to-self repeats the topic word more often than prose about it does.

   Every entry carries its reason, and the reasons are emitted into the
   generated file so the exclusion is auditable rather than mysterious.
   ========================================================================== */

const SUPERSEDED: Record<string, string> = {
  c9: 'FAQ answer describing WebLLM streaming inference on this site — the shipped site runs no model',
  c14: 'engineer intro claiming a static export with transformers.js retrieval and WebLLM inference',
  c15: 'founder intro citing "the in-browser LLM answering questions on this page"',
  c16: 'the portfolio-RAG write-up: Qwen2.5-1.5B on WebGPU, an architecture that was never shipped',
  c17: 'CRM outline with unanswered questions and empty metrics — superseded by /work/crm',
  c18: 'lead-engine outline, questions to self — superseded by /work/leadhouse',
  c19: 'ads-analyser outline, questions to self — superseded by /work/ads-analyser',
  c20: 'voiceover-platform outline, questions to self — superseded by /work/studio',
}

type AskChunk = {
  id: string
  source: string
  label: string
  href: string | null
  text: string
}

/** Collapses whitespace and normalises the typographic characters that make a
    quoted sentence look mangled when it is pulled out of prose. */
function flatten(text: string): string {
  return text.replace(/\s+/g, ' ').trim()
}

/**
 * Splits prose into sentences, then packs them into chunks of at most
 * ASK_CHUNK_MAX characters.
 *
 * Sentence-aware packing rather than a hard character slice, because a chunk
 * that ends mid-sentence produces a citation that ends mid-sentence, and the
 * whole promise of this feature is that what you read is what he wrote.
 */
function packSentences(text: string): string[] {
  const flat = flatten(text)
  if (flat.length <= ASK_CHUNK_MAX) return flat.length > 0 ? [flat] : []

  /* Conservative sentence boundary: a terminator, whitespace, then something
     that starts a sentence. Written as a match rather than a split with a
     lookbehind, because lookbehind is still not universal in Safari and a
     regex that throws at parse time would take the whole module with it. */
  const pieces = flat.match(/[^.!?]+[.!?]+(?=\s|$)\s*|[^.!?]+$/g) ?? [flat]

  const out: string[] = []
  let current = ''
  for (const piece of pieces) {
    const next = current.length > 0 ? `${current}${piece}` : piece
    if (next.length > ASK_CHUNK_MAX && current.length > 0) {
      out.push(current.trim())
      current = piece
    } else {
      current = next
    }
  }
  if (current.trim().length > 0) out.push(current.trim())

  /* Merge runt chunks into their neighbour.

     BM25 normalises by document length, so a very short chunk that happens to
     contain two of the query's terms outranks a long, genuinely relevant one.
     A real case: the six-word chunk "Chose: Build the signing flow in the CRM."
     beat the whole write-up of working with an AI pair on the query "did he
     use AI to build the CRM?" — it contained "build" and "CRM" and nothing
     else, so its term density was unbeatable and its relevance was nil.

     Merging runts forward keeps every chunk long enough for length
     normalisation to mean something. It is a retrieval-quality fix rather than
     a fix for one query: any sentence short enough to be a label was always
     going to win queries it should lose. */
  const merged: string[] = []
  for (const piece of out) {
    const previous = merged[merged.length - 1]
    if (piece.length < ASK_CHUNK_MIN && previous !== undefined) {
      merged[merged.length - 1] = `${previous} ${piece}`.trim()
    } else {
      merged.push(piece)
    }
  }

  /* A leading runt has no previous neighbour, so it merges backwards into the
     one that follows it instead. */
  if (merged.length > 1 && (merged[0]?.length ?? 0) < ASK_CHUNK_MIN) {
    merged[1] = `${merged[0]} ${merged[1]}`.trim()
    merged.shift()
  }

  return merged
}

/** ~52 characters of human label, so a source chip reads as a place. */
function shortLabel(text: string): string {
  const flat = flatten(text)
  if (flat.length <= 52) return flat
  const clipped = flat.slice(0, 52)
  const space = clipped.lastIndexOf(' ')
  return `${(space > 20 ? clipped.slice(0, space) : clipped).replace(/[\s,;:—–-]+$/, '')}…`
}

/**
 * Cuts the supplementary chunks out of the site's own content modules.
 *
 * Deliberately NOT everything. The CV is skipped entirely, because the 23
 * embedded chunks already are the CV — indexing it twice would put two
 * near-identical documents at the top of every employment query and cost the
 * bundle for the privilege. What is added is the two bodies of prose the index
 * has never seen: the about page, and the ten-part case studies.
 */
async function buildAskSupplement(): Promise<AskChunk[]> {
  /* Imported for their real, validated shape rather than parsed out of the
     source text. lib/content.ts runs every project through Zod at module load,
     so a corpus built from it cannot contain a chunk that the site itself would
     refuse to render. */
  const { projects, hasProjectPage, decisions, incidents } = await import('../lib/content')
  const { site } = await import('../lib/site.config')

  const chunks: AskChunk[] = []
  const add = (source: string, href: string | null, label: string, text: string): void => {
    for (const [index, part] of packSentences(text).entries()) {
      chunks.push({
        id: `${source}-${String(chunks.length + 1).padStart(2, '0')}`,
        source,
        href,
        label: index === 0 ? label : `${label} (cont.)`,
        text: part,
      })
    }
  }

  /* --- The about page ---------------------------------------------------- */
  for (const section of site.about.sections) {
    /* The heading is prepended to the body because it carries terms the body
       assumes: "What I have learned" is where the security-audit lesson lives,
       and the body never uses the word "learned". */
    add('about', '/about', section.heading, `${section.heading}. ${section.body}`)
  }
  add(
    'about',
    '/about',
    'Timeline',
    `Timeline. ${site.about.timeline.map((entry) => `${entry.year}: ${entry.event}`).join(' ')}`,
  )

  /* One templated chunk, and the only templated one. Every value in it is a
     field of site.config — location, timezone, availability, role, email — and
     the sentence exists because the structured fields say "Gurgaon, India"
     while a visitor asks "where is he based?". Retrieval matches words, so the
     words a person would use have to be in the corpus somewhere. This is
     formatting, not authorship: no claim here that site.config does not make. */
  add(
    'profile',
    '/about',
    'Location and availability',
    `Location and availability. ${site.name} is based in ${site.location}, and works in ` +
      `the ${site.timezone} time zone (${site.timezoneLabel}). His role is ${site.role}. ` +
      `Current status: ${site.availability}. He can be reached by email at ${site.email}.`,
  )

  /* --- The case studies -------------------------------------------------- */
  /* Adds a chunk only when the field exists. With the depth ladder in
     lib/schema.ts, six of the ten case-study parts are absent on a supporting
     project and most are absent on an archive entry — so this is now the
     normal case, not an edge case. Skipping is the whole behaviour: a chunk
     built from an undefined field would index the string "undefined" and the
     retrieval probes would start matching it. */
  const addIf = (
    source: string,
    href: string | null,
    label: string,
    text: string | undefined,
  ): void => {
    if (text) add(source, href, label, text)
  }

  for (const project of projects) {
    const source = `work/${project.slug}`
    /* Archive entries have no page (lib/content.ts, hasProjectPage), so their
       chunks cite the work index. Citing /work/<slug> would hand the chat a
       confident link to a 404 — the one failure mode that makes a retrieval
       answer worse than no answer. */
    const href = hasProjectPage(project) ? `/work/${project.slug}` : '/work'

    /* An overview chunk, assembled from the project's structured fields, so a
       query naming the technology finds the project even when the prose below
       never spells the stack out in one place. */
    const stack = project.stack.map((item) => item.name).join(', ')
    add(
      source,
      href,
      project.title,
      `${project.title}. ${project.tagline} Role: ${project.role}. Status: ${project.status}, ` +
        `${project.year}${project.duration ? `, ${project.duration}` : ''}. ` +
        `Built for ${project.client ?? project.clientDescriptor ?? 'an undisclosed client'}. ` +
        `Stack: ${stack}.`,
    )

    add(source, href, `${project.title} — context`, project.context)
    addIf(source, href, `${project.title} — the problem`, project.problem)
    addIf(source, href, `${project.title} — approach`, project.approach)
    addIf(source, href, `${project.title} — implementation`, project.implementation)

    /* One chunk per challenge, rather than one chunk listing all of them.
       The items are separate statements and most do not end in a full stop, so
       joining them produces a single run-on "sentence" — and the quotation for
       "what did the security audit find?" came back as the CSV-parsing
       challenge, because both were inside the same unbreakable blob. Splitting
       at the boundary that already exists in the data is better than inserting
       punctuation he did not write. */
    const challenges = project.challenges ?? []
    for (const [index, challenge] of challenges.entries()) {
      add(
        source,
        href,
        `${project.title} — what was hard (${index + 1}/${challenges.length})`,
        challenge,
      )
    }
    addIf(source, href, `${project.title} — how it was solved`, project.solution)
    add(source, href, `${project.title} — outcome`, project.outcome)
    addIf(source, href, `${project.title} — in hindsight`, project.reflection)


  /* Metrics are templated from the same objects the case-study page renders,
       including the source and capture date. A number without its provenance
       is exactly what lib/schema.ts exists to prevent, so the provenance
       travels with it into the corpus. */
    if (project.metrics.length > 0) {
      const measured = project.metrics
        .map(
          (metric) =>
            `${metric.label}: ${metric.after}` +
            `${metric.before ? ` (from ${metric.before})` : ''}` +
            ` — ${metric.source}, measured ${metric.capturedAt}.` +
            `${metric.note ? ` ${metric.note}` : ''}`,
        )
        .join(' ')
      add(source, href, `${project.title} — measured results`, `Measured results. ${measured}`)
    }
  }

    /* --- The decision log and the failure archive --------------------------

     These were missing from the corpus, and their absence was worse than a
     gap: they are the highest-signal content on the site, and leaving them
     out meant the chat refused questions the site answers in full three
     clicks away. On one topic in particular that refusal read as evasion
     rather than as honest scope — "did you use AI to build this?" is
     documented as a decision with its trade-off paid in the failure archive,
     and a chat that says "there is nothing here about that" about openly
     published content is not being careful, it is being wrong.

     Each decision is split at its own field boundaries rather than indexed as
     one blob, for the same reason the challenges are: "what did you trade
     away" and "what happened" are different questions and want to be
     different chunks. */
  for (const decision of decisions) {
    const source = `thinking/${decision.id}`
    const href = `/thinking#${decision.id}`

    /* The projects a decision belongs to are named INSIDE its chunks, not just
       linked from them. Without this, "did he use AI to build the CRM?" scored
       the e-signatures decision higher than the one about working with an AI
       pair — because that chunk happened to contain both "build" and "CRM"
       while the right answer contained neither. BM25 cannot know that a
       decision tagged `projects: ['crm']` is about the CRM; the vocabulary has
       to actually be in the text. */
    const about = decision.projects
      .map((slug) => projects.find((p) => p.slug === slug)?.title)
      .filter((title): title is string => Boolean(title))
    const scope = about.length > 0 ? ` This decision is about ${about.join(' and ')}.` : ''

    add(source, href, decision.question, `${decision.question} ${decision.context}${scope}`)
    add(
      source,
      href,
      `${decision.question} — what was chosen`,
      `Chose: ${decision.chose}. ${decision.because}${scope}`,
    )
    add(source, href, `${decision.question} — the trade-off`, decision.tradeoff)
    add(
      source,
      href,
      `${decision.question} — outcome`,
      `${decision.outcome} Would do it again: ${decision.wouldRepeat}.`,
    )
    for (const option of decision.options) {
      const pros = option.pros.join('. ')
      const cons = option.cons.join('. ')
      add(
        source,
        href,
        `${decision.question} — option considered: ${option.name}`,
        `${option.name}. In favour: ${pros}. Against: ${cons}.`,
      )
    }
  }

  for (const incident of incidents) {
    const source = `failures/${incident.id}`
    const href = `/thinking#${incident.id}`
    add(source, href, `${incident.title} — what happened`, `${incident.symptom} ${incident.impact}`)
    add(source, href, `${incident.title} — cause`, incident.cause)
    add(source, href, `${incident.title} — the fix`, incident.fix)
    add(source, href, `${incident.title} — what it taught`, incident.lesson)
  }

  return chunks
}

/* ==========================================================================
   WITHHELD TOPICS — the questions the site deliberately does not answer

   Retrieval can only refuse two ways on its own: nothing matched, or nothing
   matched well enough. Neither covers the case where the corpus contains the
   QUESTION but not the ANSWER — lib/site.config.ts lists a notice period and a
   visa status as fields, and their values are still `[TO CONFIRM]`. BM25 sees
   the label, scores the chunk, and would quote a field name back as though it
   were a fact.

   So the unfilled logistics fields are emitted as explicit withheld topics,
   derived from the same placeholders that `npm run check:content` already
   reports. This is not a blocklist of awkward questions: it is the honest
   consequence of a field that has no value yet, and when Dheeraj fills one in,
   the next build drops it from this list automatically.
   ========================================================================== */

/* Two regexes for one pattern on purpose: a /g regex carries lastIndex between
   calls, so using the same object to test and to strip makes the second call
   depend on where the first one stopped. */
const HAS_PLACEHOLDER = /\[[^\]]+\]/
const ALL_PLACEHOLDERS = /\[[^\]]+\]/g

type Withheld = { topic: string; terms: string[]; reason: string }

async function buildWithheld(): Promise<Withheld[]> {
  const { site } = await import('../lib/site.config')
  const stopwords = new Set(['to', 'in', 'of', 'or', 'and', 'the', 'a', 'an'])

  const out: Withheld[] = []
  for (const field of site.cv.logistics) {
    if (!HAS_PLACEHOLDER.test(field.value)) continue

    /* Whatever survives once the placeholder is removed is a real stated
       position — "Salary expectations: Discussed at offer stage." is a stance,
       even though the bracketed note beside it is unresolved. It becomes the
       refusal's reason, so the refusal says what the site says rather than
       inventing a softer version of it. */
    const stated = field.value.replace(ALL_PLACEHOLDERS, '').replace(/\s+/g, ' ').trim()

    const terms = field.label
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter((term) => term.length > 1 && !stopwords.has(term))

    out.push({
      topic: field.label.toLowerCase(),
      terms,
      reason:
        stated.length > 0
          ? `On “${field.label.toLowerCase()}” the CV states only this: ${stated} Anything more precise is Dheeraj's to tell you himself.`
          : `The CV lists “${field.label.toLowerCase()}” as a field and leaves its value to be confirmed, so there is nothing published here to quote.`,
    })
  }
  return out
}

/* ==========================================================================
   EMIT
   ========================================================================== */

function round(value: number, places: number): number {
  const factor = 10 ** places
  // +0 collapses -0 to 0; a signed zero in the output is noise in the diff.
  return Math.round(value * factor) / factor + 0
}

async function main(): Promise<void> {
  const chunks = loadIndex()
  const projection = pca2(chunks)

  const bpe = trainBpe(chunks)
  const corpus = chunks.map((chunk) => chunk.text).join('\n')
  const corpusChars = Array.from(corpus).length
  const corpusTokens = encodeWith(bpe.merges, corpus).length
  const corpusRatio = corpusTokens > 0 ? corpusChars / corpusTokens : 1

  const sources = [...new Set(chunks.map((chunk) => chunk.source))]

  const points = chunks.map((chunk, index) => ({
    id: chunk.id,
    source: chunk.source,
    label: labelFor(chunk.text),
    x: round(projection.coords[index]?.x ?? 0, 4),
    y: round(projection.coords[index]?.y ?? 0, 4),
    text: chunk.text.replace(/\s+/g, ' ').trim(),
  }))

  const pct = (value: number): string => `${(value * 100).toFixed(1)}%`

  const header = `/* ==========================================================================
   LAB DATA — GENERATED. DO NOT EDIT.

   Written by scripts/build-lab-data.ts. Run \`npm run build:lab\` to rebuild.
   Source: the RAG index of Dheeraj's CV, FAQ, intros and project write-ups —
   ${chunks.length} chunks, each embedded with bge-small-en-v1.5 (${projection.mean.length} dimensions,
   L2-normalised).

   ── PCA, MEASURED ─────────────────────────────────────────────────────────
   Two components, computed by power iteration on the ${chunks.length}x${chunks.length} Gram matrix of
   the mean-centred vectors, then deflation.

     component 1   ${pct(projection.explained1)} of total variance
     component 2   ${pct(projection.explained2)} of total variance
     together      ${pct(projection.explained)}

   That is a real number, not a flattering one, and the instrument states it
   on screen. ${pct(1 - projection.explained)} of the structure in this corpus does not fit on a
   flat picture — which is the honest lesson of the map, and the reason no
   claim is made that visual distance equals semantic distance exactly.

   Both axes share one scale factor (${round(projection.scale, 4)}), so the plot's aspect ratio
   reflects the real ratio between the components rather than stretching the
   weaker axis to fill the box.

   ── BPE, MEASURED ─────────────────────────────────────────────────────────
   ${bpe.merges.length} merges trained on the same ${chunks.length} chunks. On the training corpus:

     ${corpusChars} characters -> ${corpusTokens} tokens   (${corpusRatio.toFixed(2)} chars/token)

   A production tokeniser has ~100k merges trained on the open web and would
   reach roughly 4 chars/token on English prose. This one is domain-specific
   by construction: it knows "WordPress" and "Companies House" as single
   tokens and has never seen the word "banana".
   ========================================================================== */
`

  const body = `
export type LabPoint = {
  /** Chunk id from the RAG index. */
  id: string
  /** Source document the chunk came from. */
  source: string
  /** ~40-character human label, derived from the chunk's opening phrase. */
  label: string
  /** PCA coordinates, shared scale, both within [-1, 1]. */
  x: number
  y: number
  /** Full chunk text, whitespace collapsed. Used for lexical retrieval. */
  text: string
}

/** The corpus, projected. Document order matches the index. */
export const LAB_POINTS: LabPoint[] = ${JSON.stringify(points, null, 2)}

/** Distinct sources, in first-appearance order. Drives the legend and hues. */
export const LAB_SOURCES: { id: string; label: string }[] = ${JSON.stringify(
    sources.map((source) => ({ id: source, label: sourceLabel(source) })),
    null,
    2,
  )}

/** Fraction of total variance retained by the two plotted components. */
export const PCA_EXPLAINED_VARIANCE = ${round(projection.explained, 4)}
export const PCA_EXPLAINED_VARIANCE_1 = ${round(projection.explained1, 4)}
export const PCA_EXPLAINED_VARIANCE_2 = ${round(projection.explained2, 4)}

/** Embedding dimensionality the projection was fitted on. */
export const PCA_DIMENSIONS = ${projection.mean.length}

/* The fitted basis. Nothing in the shipped instruments imports these three —
   the query point is placed lexically, and saying so is the point — but they
   are emitted because they are what makes the projection reproducible and
   invertible: given a real bge-small vector q, its map position is
   ((q - PCA_MEAN) · PCA_COMPONENT_N) / PCA_SCALE. Unused named exports are
   dropped by tree-shaking, so they cost nothing in the browser. */
export const PCA_SCALE = ${round(projection.scale, 6)}
export const PCA_MEAN: number[] = ${JSON.stringify(projection.mean.map((v) => round(v, 5)))}
export const PCA_COMPONENT_1: number[] = ${JSON.stringify(
    projection.component1.map((v) => round(v, 5)),
  )}
export const PCA_COMPONENT_2: number[] = ${JSON.stringify(
    projection.component2.map((v) => round(v, 5)),
  )}

/** Ordered merge table. The order IS the model — rank decides which pair a
    word collapses first, so this array must not be sorted or de-duplicated. */
export const BPE_MERGES: [string, string][] = ${JSON.stringify(bpe.merges)}

/** Every character the training corpus contained. Anything outside this set
    is out-of-vocabulary and the tokeniser says so rather than pretending. */
export const BPE_BASE_CHARS: string[] = ${JSON.stringify(bpe.baseChars)}

/** Base characters followed by every merged token, in learning order. */
export const BPE_VOCAB: string[] = ${JSON.stringify(bpe.vocab)}

/** Measured on the training corpus at build time, for the instrument to cite. */
export const BPE_STATS = {
  chunks: ${chunks.length},
  merges: ${bpe.merges.length},
  vocabSize: ${bpe.vocab.length},
  corpusChars: ${corpusChars},
  corpusTokens: ${corpusTokens},
  charsPerToken: ${round(corpusRatio, 3)},
} as const
`

  mkdirSync(dirname(OUT_PATH), { recursive: true })
  writeFileSync(OUT_PATH, `${header}${body}`, 'utf8')

  const bytes = Buffer.byteLength(`${header}${body}`)
  console.log(`build-lab-data: PCA explained variance (2 components) ${pct(projection.explained)}`)
  console.log(
    `build-lab-data:   c1 ${pct(projection.explained1)}  c2 ${pct(projection.explained2)}`,
  )
  console.log(
    `build-lab-data: BPE ${bpe.merges.length} merges, vocab ${bpe.vocab.length}, ` +
      `${corpusRatio.toFixed(2)} chars/token on the training corpus`,
  )
  console.log(`build-lab-data: wrote ${OUT_PATH} (${(bytes / 1024).toFixed(1)} KB)`)

  await emitAskCorpus(chunks.length)
}

/** Writes content/ask-corpus.ts — the retrieval index lib/retrieval.ts scores. */
async function emitAskCorpus(indexedCount: number): Promise<void> {
  const supplement = await buildAskSupplement()
  const withheld = await buildWithheld()
  const keptCount = indexedCount - Object.keys(SUPERSEDED).length

  const supplementChars = supplement.reduce((sum, chunk) => sum + chunk.text.length, 0)
  const sources = [...new Set(supplement.map((chunk) => chunk.source))]

  const file = `/* ==========================================================================
   ASK CORPUS — GENERATED. DO NOT EDIT.

   Written by scripts/build-lab-data.ts (see the ASK CORPUS section there for
   the reasoning). Run \`npm run build:lab\` to rebuild.

   This is the corpus lib/retrieval.ts scores with BM25 and quotes verbatim.
   Two halves, and the difference matters:

     ${String(keptCount).padStart(3)} chunks  of the ${indexedCount} in the embedded RAG index, imported from
                ./lab-data rather than copied — the Lab already ships that text
                on the same page. ${Object.keys(SUPERSEDED).length} are excluded; the reasons are listed
                against each id below.
     ${String(supplement.length).padStart(3)} chunks  cut here from the site's own current content: the about
                page and the ${sources.filter((s) => s.startsWith('work/')).length} case studies. ${supplementChars} characters of prose
                that is published on a route a visitor can open and check.

   Nothing in here is written by the build. One chunk is TEMPLATED from
   structured fields (location, timezone, availability, role, email) and it is
   marked as such below; everything else is prose lifted intact.
   ========================================================================== */

import { LAB_POINTS } from '@/content/lab-data'

export type AskChunk = {
  /** Stable id. \`idx-*\` came from the embedded index; the rest were cut here. */
  id: string
  /** Which document it came from — shown on the citation chip. */
  source: string
  /** Human label for the chip, so a citation reads as a place. */
  label: string
  /** Route where this text can be read in context, or null if it has no page. */
  href: string | null
  /** The text, whitespace collapsed. Quoted verbatim; never paraphrased. */
  text: string
}

/* Where each embedded chunk can be read. The index predates the current routes,
   so this mapping is stated rather than derived. */
const INDEX_HREF: Record<string, string> = ${JSON.stringify(INDEX_HREF, null, 2)}

/* Chunks the Lab plots but this system will not quote. A picture of a corpus is
   not a claim about the world; an answer is. Reason per id:
${Object.entries(SUPERSEDED)
  .map(([id, reason]) => `     ${id.padEnd(4)} ${reason}`)
  .join('\n')}
*/
const SUPERSEDED = new Set(${JSON.stringify(Object.keys(SUPERSEDED))})

/** The embedded index, minus the superseded chunks, as retrieval chunks. */
const INDEXED: AskChunk[] = LAB_POINTS.filter((point) => !SUPERSEDED.has(point.id)).map(
  (point) => ({
    id: \`idx-\${point.id}\`,
    source: point.source,
    label: point.label,
    href: INDEX_HREF[point.source] ?? null,
    text: point.text,
  }),
)

/** Cut from lib/site.config.ts and content/projects.ts at build time. */
export const ASK_SUPPLEMENT: AskChunk[] = ${JSON.stringify(supplement, null, 2)}

/** The corpus. Index first, so ids stay stable as case studies are added. */
export const ASK_CHUNKS: AskChunk[] = [...INDEXED, ...ASK_SUPPLEMENT]

/* Topics the site itself declines to answer, derived from the unfilled
   \`[TO CONFIRM]\` placeholders in site.config's logistics block — the same
   placeholders \`npm run check:content\` reports. A withheld topic fires only
   when a query names EVERY word of the field, because one word of overlap is
   far too blunt: "roles" alone must not refuse a question about his role at
   Virtuoso, which the corpus answers perfectly well. */
export const ASK_WITHHELD: { topic: string; terms: string[]; reason: string }[] = ${JSON.stringify(
    withheld,
    null,
    2,
  )}

/** Measured at build time, for the interface to cite honestly. */
export const ASK_STATS = {
  /** Chunks taken from the embedded index. */
  indexed: ${keptCount},
  /** Chunks in the embedded index that this system will not quote. */
  superseded: ${Object.keys(SUPERSEDED).length},
  /** Chunks cut from the site's current content. */
  supplement: ${supplement.length},
  /** The corpus. This is the number the interface is allowed to state. */
  chunks: ${keptCount + supplement.length},
  supplementChars: ${supplementChars},
} as const
`

  const path = resolve(process.cwd(), 'content/ask-corpus.ts')
  writeFileSync(path, file, 'utf8')
  console.log(
    `build-lab-data: ask corpus ${keptCount} of ${indexedCount} indexed ` +
      `(${Object.keys(SUPERSEDED).length} superseded) + ${supplement.length} supplementary ` +
      `= ${keptCount + supplement.length} chunks, ${withheld.length} withheld topics`,
  )
  console.log(
    `build-lab-data: wrote ${path} (${(Buffer.byteLength(file) / 1024).toFixed(1)} KB)`,
  )
}

main().catch((cause: unknown) => {
  console.error('build-lab-data: failed')
  console.error(cause)
  process.exit(1)
})
